### ISSUE TITLE
Forms - Extended fields - Teacher field optional,  Topics trim space and update issue

### ISSUE THREAD

**Issue by sabrinasun** [sabrinasun/befree#58]
1. Linked form - Teacher field in link form is not required.  

2. Both forms - Beginning and ending spaces in topics fields are not trimmed before saving to database. This causes duplicated topics. " pureland " and "pureland" are considered different. Please trim.  

3. Both forms - Topics update doesn't remove previous topics. Say user first entered:
topic 1, topic2, topic3 
and then updated with 
topic 1
Please simply remove previous topics for this post, then add new topics. 
The current behavior is strange, can't remove previous topics through update

4. Both formss - look ahead is not implemented at all. We can leave for future though if can't implement now.

**Comment by vaimdev** [comment]
Note on the bugs, and will fix them.
> 4. Both formss - look ahead is not implemented at all. We can leave for future though if can't implement now.
The look ahead for Teacher field already implemented , maybe some javascript cause problem ?
There must have existing teacher records in the db , then only the look ahead will work.

**Comment by sabrinasun** [comment]
Thanks.  Yes I see teacher's look ahead is implemented. Yes we can leave the rest for future.

**Comment by vaimdev** [comment]
Fixed and updated to server

**Comment by sabrinasun** [comment]
1. Not fixed = Teacher field in Extend form is optional. It is still required. 
2. Fixed. 
3. Fixed.
4. Fixed.

**Comment by vaimdev** [comment]
Item (1) fixed and updated to test site.

**Comment by sabrinasun** [comment]
All fixed.
